import UInt256.Methods.Multiply.ReturnCorrectness
#print axioms UInt256Proof.Multiply.return_checked_contract
#print axioms UInt256Proof.Multiply.return_checked_profile_contract
#print axioms UInt256Proof.Multiply.return_checked_family_contract
