import UInt256.Methods.Multiply.ScalarUInt32LeftCorrectness
#print axioms UInt256Proof.Multiply.scalar_return_checked_contract
#print axioms UInt256Proof.Multiply.scalar_return_checked_profile_contract
#print axioms UInt256Proof.Multiply.scalar_return_checked_family_contract
