using System.Text;
using System.Text.Json;
using Mono.Cecil;
using Mono.Cecil.Cil;

internal static class LeanEmitter
{
    internal static (string Lean, List<object> Coverage) Generate(MethodDefinition[] methods)
    {
        StringBuilder lean = new("-- Generated by Extractor v1. DO NOT EDIT.\nimport CIL.Semantics\nnamespace Extracted\nopen CIL\n");
        List<object> coverage = [];
        for (int methodIndex = 0; methodIndex < methods.Length; methodIndex++)
        {
            MethodDefinition m = methods[methodIndex];
            var instructions = m.Body.Instructions;
            HashSet<Instruction> reachable = Reachability.Analyze(m);
            lean.Append($"def method{methodIndex} : Method := {{\n  returnsValue := {(m.ReturnType.FullName == "System.Void" ? "false" : "true")}\n  locals := [");
            lean.Append(string.Join(", ", m.Body.Variables.Select(v => v.VariableType.FullName switch
            {
                "System.UInt64" => ".i64 0",
                "System.Boolean" or "System.Int32" => ".i32 0",
                "Nethermind.Int256.UInt256&" => ".nullRef",
                string s when s.StartsWith("System.Runtime.Intrinsics.Vector256`1<", StringComparison.Ordinal) => ".unmodeled",
                _ => throw new InvalidDataException($"Unsupported local type {v.VariableType.FullName}")
            })));
            lean.Append("]\n  code := [\n");
            List<string> ops = [];
            foreach (Instruction i in instructions)
            {
                bool live = reachable.Contains(i);
                string op;
                try { op = InstructionTranslation.Translate(i, m, methods, methodIndex); }
                catch (InvalidDataException) when (!live) { op = $".unsupported {JsonSerializer.Serialize(i.ToString())}"; }
                ops.Add($"    {op}, -- IL_{i.Offset:x4}{(live ? "" : " (unreachable with intrinsics disabled)")}");
            }
            lean.Append(string.Join("\n", ops));
            lean.Append("\n  ] }\n\n");
            coverage.Add(new { method = m.FullName, reachable = reachable.Select(i => i.Offset).Order().ToArray(),
                excluded = instructions.Where(i => !reachable.Contains(i)).Select(i => i.Offset).ToArray() });
        }
        lean.Append("def program : Program := [method0, method1, method2, method3, method4]\nend Extracted\n");
        return (lean.ToString(), coverage);
    }
}
