using System.Text;
using System.Text.Json;
using Mono.Cecil;
using Mono.Cecil.Cil;

internal static class LeanEmitter
{

    internal static (string Lean, List<object> Coverage) Generate(MethodDefinition[] methods)
    {
        StringBuilder lean = new("-- Generated by Extractor v3. DO NOT EDIT.\nimport CIL.SymbolicExecution\nset_option maxRecDepth 8192\nnamespace Extracted\nopen CIL\n");
        List<object> coverage = [];
        for (int methodIndex = 0; methodIndex < methods.Length; methodIndex++)
        {
            MethodDefinition m = methods[methodIndex];
            var instructions = m.Body.Instructions;
            HashSet<Instruction> reachable = Reachability.Analyze(m);
            string symbol = $"method{methodIndex}";
            string returnsValue = m.ReturnType.FullName == "System.Void" ? "false" : "true";
            lean.Append($"@[cil_code] def {symbol}Index : Nat := {methodIndex}\n");
            string locals = string.Join(", ", m.Body.Variables.Select(v => v.VariableType.FullName switch
            {
                "System.UInt64" => ".i64 0",
                "System.Boolean" or "System.Int32" => ".i32 0",
                "Nethermind.Int256.UInt256&" or "System.UInt64&" => ".nullRef",
                string s when s.StartsWith("System.Runtime.Intrinsics.Vector256`1<", StringComparison.Ordinal) => ".unmodeled",
                _ => throw new InvalidDataException($"Unsupported local type {v.VariableType.FullName}")
            }));
            // Keep the body folded during execution simplification. Its fields
            // and concrete instruction fetches have separately checked equations.
            lean.Append($"def {symbol}Body : Method := {{\n  returnsValue := {returnsValue}\n  locals := [{locals}]\n  code := [\n");
            List<string> ops = [];
            List<string> lookups = [];
            for (int instructionIndex = 0; instructionIndex < instructions.Count; instructionIndex++)
            {
                Instruction i = instructions[instructionIndex];
                bool live = reachable.Contains(i);
                string op;
                op = live ? InstructionTranslation.Translate(i, m, methods, methodIndex)
                    : $".unsupported {JsonSerializer.Serialize(i.ToString())}";
                ops.Add($"    {op}, -- IL_{i.Offset:x4}{(live ? "" : " (unreachable in the selected environment)")}");
                lookups.Add($"@[cil_code ↓] theorem {symbol}Instruction{instructionIndex} : " +
                    $"{symbol}Body.code[{instructionIndex}]? = some ({op}) := by rfl\n");
            }
            lean.Append(string.Join("\n", ops));
            lean.Append("\n  ] }\n\n");
            lean.Append($"@[cil_code] theorem {symbol}Locals : {symbol}Body.locals = [{locals}] := by rfl\n");
            lean.Append($"@[cil_code] theorem {symbol}Returns : {symbol}Body.returnsValue = {returnsValue} := by rfl\n");
            lean.Append($"@[cil_code] theorem {symbol}Length : {symbol}Body.code.length = {instructions.Count} := by rfl\n");
            lean.Append(string.Join("", lookups));
            lean.Append('\n');
            coverage.Add(new { method = m.FullName, reachable = reachable.Select(i => i.Offset).Order().ToArray(),
                excluded = instructions.Where(i => !reachable.Contains(i)).Select(i => i.Offset).ToArray() });
        }
        lean.Append($"def program : Program := [{string.Join(", ", Enumerable.Range(0, methods.Length).Select(i => $"method{i}Body"))}]\n");
        for (int methodIndex = 0; methodIndex < methods.Length; methodIndex++)
        {
            string symbol = $"method{methodIndex}";
            lean.Append($"@[cil_code] theorem {symbol}Member : program[{methodIndex}]? = some {symbol}Body := by rfl\n");
            int bound = methods.Skip(methodIndex).Sum(m => Reachability.Analyze(m).Count) + 1;
            lean.Append($"@[cil_code] theorem {symbol}Bound : executionBound program {methodIndex} = {bound} := by rfl\n");
        }
        int entryIndex = Array.FindIndex(methods, m => m.FullName == MetadataValidation.EntrySignature);
        if (entryIndex < 0) throw new InvalidDataException("Public entry missing from discovered dependencies");
        lean.Append($"@[cil_code] def entryIndex := method{entryIndex}Index\n@[cil_code] def entryBody := method{entryIndex}Body\n");
        foreach (var group in methods.Select((method, index) => new { Role = MetadataValidation.Role(method), Index = index })
                     .Where(candidate => candidate.Role is not null).GroupBy(candidate => candidate.Role))
        {
            // Ambiguous candidates simply receive no optional role; raw stepping
            // remains available and extraction does not reject a decomposition.
            if (group.Count() != 1) continue;
            int index = group.Single().Index;
            lean.Append($"@[cil_code] def {group.Key}Index := method{index}Index\n");
            lean.Append($"@[cil_code] def {group.Key}Body := method{index}Body\n");
        }
        lean.Append("end Extracted\n");
        return (lean.ToString(), coverage);
    }
}
