using System.Text;
using System.Text.Json;
using Mono.Cecil;
using Mono.Cecil.Cil;

internal static class LeanEmitter
{
    private static string Symbol(MethodDefinition method) => char.ToLowerInvariant(method.Name[0]) + method.Name[1..];

    internal static (string Lean, List<object> Coverage) Generate(MethodDefinition[] methods)
    {
        StringBuilder lean = new("-- Generated by Extractor v2. DO NOT EDIT.\nimport CIL.SymbolicExecution\nset_option maxRecDepth 8192\nnamespace Extracted\nopen CIL\n");
        List<object> coverage = [];
        for (int methodIndex = 0; methodIndex < methods.Length; methodIndex++)
        {
            MethodDefinition m = methods[methodIndex];
            var instructions = m.Body.Instructions;
            HashSet<Instruction> reachable = Reachability.Analyze(m);
            string symbol = Symbol(m);
            lean.Append($"@[cil_code] def {symbol}Index : Nat := {methodIndex}\n");
            lean.Append($"@[cil_code] def {symbol}Body : Method := {{\n  returnsValue := {(m.ReturnType.FullName == "System.Void" ? "false" : "true")}\n  locals := [");
            lean.Append(string.Join(", ", m.Body.Variables.Select(v => v.VariableType.FullName switch
            {
                "System.UInt64" => ".i64 0",
                "System.Boolean" or "System.Int32" => ".i32 0",
                "Nethermind.Int256.UInt256&" => ".nullRef",
                string s when s.StartsWith("System.Runtime.Intrinsics.Vector256`1<", StringComparison.Ordinal) => ".unmodeled",
                _ => throw new InvalidDataException($"Unsupported local type {v.VariableType.FullName}")
            })));
            lean.Append("]\n  code := [\n");
            List<string> ops = [];
            foreach (Instruction i in instructions)
            {
                bool live = reachable.Contains(i);
                string op;
                try { op = InstructionTranslation.Translate(i, m, methods, methodIndex); }
                catch (InvalidDataException) when (!live) { op = $".unsupported {JsonSerializer.Serialize(i.ToString())}"; }
                ops.Add($"    {op}, -- IL_{i.Offset:x4}{(live ? "" : " (unreachable with intrinsics disabled)")}");
            }
            lean.Append(string.Join("\n", ops));
            lean.Append("\n  ] }\n\n");
            coverage.Add(new { method = m.FullName, reachable = reachable.Select(i => i.Offset).Order().ToArray(),
                excluded = instructions.Where(i => !reachable.Contains(i)).Select(i => i.Offset).ToArray() });
        }
        lean.Append($"def program : Program := [{string.Join(", ", methods.Select(m => Symbol(m) + "Body"))}]\n");
        for (int methodIndex = 0; methodIndex < methods.Length; methodIndex++)
        {
            string symbol = Symbol(methods[methodIndex]);
            lean.Append($"@[cil_code] theorem {symbol}Member : program[{methodIndex}]? = some {symbol}Body := by rfl\n");
            int bound = methods.Skip(methodIndex).Sum(m => m.Body.Instructions.Count) + 1;
            lean.Append($"@[cil_code] theorem {symbol}Bound : executionBound program {methodIndex} = {bound} := by rfl\n");
        }
        lean.Append("end Extracted\n");
        return (lean.ToString(), coverage);
    }
}
