"""Kernel-check allocation-safety foundations in a fresh isolated Lean package.

This is foundation evidence, not a combined production verification command.
"""

import json
from pathlib import Path
import shutil
import sys
import tempfile
import time

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from common import ROOT, VERIFY, run, sha, source_files
from verify import theorem_audits

AUDITS = (
    "CIL.Safety.access_alignment_at_placement",
    "CIL.Safety.loadValue_checked_read",
    "CIL.Safety.loadValue_access_requirements",
    "CIL.Safety.storeValue_checked_write",
    "CIL.Safety.storeValue_access_requirements",
    "CIL.Safety.Tests.unaligned_access_allowed",
    "CIL.Safety.Tests.aligned_access_rejected",
    "UInt256Model.Safety.output_initialization_prefix",
    "UInt256Model.Safety.OrderedScalarContract.reprofile",
    "UInt256Model.Safety.CallingConditions.after_readonly_call",
    "UInt256Model.Safety.CallingConditions.input_value_of_caller_eq",
    "UInt256Model.Safety.binary_return_setup",
    "UInt256Model.Safety.binary_return_contract",
    "UInt256Model.Safety.binary_return_checked",
    "UInt256Model.Safety.output_encoded_read",
    "CIL.Safety.byteNumber_lt",
    "CIL.Safety.numberBytes_byteNumber",
    "CIL.Safety.read_slice_bytes",
    "CIL.Safety.staticReference_preserves_memory_below",
    "CIL.Safety.word_frame_setup",
    "CIL.Safety.numeric_frame_setup",
    "UInt256Model.Safety.CallingConditions.after_preserving_inputs",
    "CIL.Safety.step_arguments_eq",
    "CIL.Safety.run_arguments_eq",
    "CIL.Safety.invoke_arguments_eq",
    "UInt256Model.Safety.ReportingBinaryContract.reprofile",
    "UInt256Model.Safety.ScalarOperatorContract.result_congr",
    "UInt256Model.Safety.ScalarValueContract.reprofile",
    "UInt256Model.Safety.InitializedBinaryContract.to_wrapping",
    "UInt256Model.Safety.InitializedUnaryContract.reprofile",
    "CIL.Safety.concreteAddress_bounds",
    "CIL.Safety.concreteAddress_injective",
    "CIL.Safety.access_guaranteed_alignment",
    "CIL.Safety.checked_access_aligned_at_placement",
    "CIL.Safety.relocation_preserves_step",
    "CIL.Safety.relocation_preserves_execution",
    "CIL.Safety.relocation_preserves_invocation",
    "CIL.Safety.enterFrame_profile",
    "CIL.Safety.step_profile_eq",
    "CIL.Safety.run_reprofile_eq",
    "CIL.Safety.invoke_reprofile_eq",
    "CIL.Safety.invoke_uniform_reprofile_eq",
    "CIL.Safety.programStaticDescriptors_reprofile",
    "CIL.Safety.invocationCertificate_reprofile",
    "CIL.Safety.invocationCertificate_uniform_reprofile",
    "CIL.Safety.Tests.relocation_changes_incidental_alignment",
    "CIL.Safety.Tests.incidental_alignment_rejected",
    "UInt256Model.Safety.callingConditions_reprofile",
    "UInt256Model.Safety.ReadOnlyContract.reprofile",
    "UInt256Model.Safety.ReadOnlyScalarContract.reprofile",
    "UInt256Model.Safety.ReadOnlyValueContract.reprofile",
    "UInt256Model.Safety.ScalarOperatorContract.reprofile",
    "UInt256Model.Safety.WrappingBinaryContract.reprofile",
    "UInt256Model.Safety.unsigned_scalar_flag",
    "UInt256Model.Safety.signed_scalar_flag",
    "UInt256Model.Safety.scalar_embedding",
    "UInt256Model.Safety.certify_readOnly_scalar",
    "UInt256Model.Safety.CallingConditions.store_private_aggregate",
    "UInt256Model.Safety.CallingConditions.with_writable_output",
    "UInt256Model.Safety.CallingConditions.new_value",
    "CIL.Safety.read_of_cover",
    "UInt256Model.Safety.output_snapshot_of_limb_reads",
    "UInt256Model.Safety.output_load_of_limb_reads",
    "CIL.Safety.allocate_initialized256",
    "CIL.Safety.step_newValue",
    "CIL.Safety.store_numeric_local",
    "CIL.Safety.load_numeric_local",
    "CIL.Safety.store_load_numeric_local",
    "CIL.Safety.make_numeric_local",
    "CIL.Safety.step_load_numeric_local",
    "CIL.Safety.step_store_numeric_local",
    "CIL.Safety.NumericHomes.weaken",
    "CIL.Safety.make_numeric_locals",
    "CIL.Safety.NumericHomes.home_at",
    "CIL.Safety.NumericHomes.home_bound",
    "CIL.Safety.NumericHomes.ordered",
    "UInt256Model.Safety.write_four_limbs",
    "CIL.Safety.run_construct_of_invoke",
    "CIL.Safety.run_construct_exists",
    "UInt256Model.Safety.CallingConditions.with_readable_input",
    "CIL.Safety.make_argument_home256",
    "UInt256Model.Safety.inputValue_of_encoded_read",
    "UInt256Model.Safety.certify_readOnly_binary_frame",
    "UInt256Model.Safety.CallingConditions.input_half_address",
    "UInt256Model.Safety.CallingConditions.input_half_load",
    "UInt256Model.Safety.CallingConditions.input_half_formed",
    "UInt256Model.Safety.certify_readOnly_binary",
    "UInt256Model.Safety.CallingConditions.swap_binary_inputs",
    "UInt256Model.Safety.forward_readOnly_binary",
    "UInt256Model.Safety.compose_readOnly_binary",
    "CIL.Safety.run_negation_return",
    "UInt256Model.Safety.CallingConditions.readOnly_arguments_valid",
    "UInt256Model.Safety.CallingConditions.readOnly_setup_succeeds",
    "CIL.Safety.Tests.full_output_initialization",
    "CIL.Safety.Tests.overlapping_snapshot",
    "CIL.Safety.Tests.invalid_intermediate",
    "CIL.Safety.Tests.recycled_slot_distinct_identity",
    "CIL.Safety.add_preserves_provenance",
    "CIL.Safety.formed_reference_live",
    "CIL.Safety.access_within_allocation",
    "CIL.Safety.access_requires_permission",
    "CIL.Safety.expired_reference",
    "CIL.Safety.write_initializes",
    "CIL.Safety.read_requires_initialization",
    "CIL.Safety.relocation_preserves_reference_validity",
    "CIL.Safety.relocation_preserves_read",
    "CIL.Safety.guaranteed_alignment_at_placement",
    "CIL.Safety.Tests.overlapping_valid_initial_call",
    "CIL.Safety.Tests.initialized_output_readable",
    "CIL.Safety.Tests.write_does_not_expose_neighbor",
    "CIL.Safety.Tests.overlapping_output_readable_after_copy",
    "CIL.Safety.write_preserves_write_permission",
    "CIL.Safety.write_read_permission",
    "CIL.Safety.write_preserves_wellFormed",
    "CIL.Safety.expire_preserves_wellFormed",
    "CIL.Safety.allocate_preserves_wellFormed",
    "CIL.Safety.Tests.actual_overread_discarded",
    "CIL.Safety.Tests.canonical_boolean_bitcasts",
    "CIL.Safety.Tests.noncanonical_boolean_bitcasts_rejected",
    "CIL.Safety.Tests.actual_invalid_reference_then_repaired",
    "CIL.Safety.Tests.actual_forbidden_write_then_restored",
    "CIL.Safety.Tests.actual_partial_vector_initialization",
    "CIL.Safety.Tests.actual_expired_field_address",
    "CIL.Safety.Tests.actual_vector_snapshot_copy",
    "CIL.Safety.instruction_fault_cannot_be_erased",
    "CIL.Safety.successful_instruction_prefix",
    "CIL.Safety.Tests.local_address_aliases_local_value",
    "CIL.Safety.Tests.nested_call_preserves_numeric_result",
    "CIL.Safety.Tests.nested_uninitialized_local_rejected",
    "CIL.Safety.Tests.escaped_local_rejected_before_caller_resumes",
    "CIL.Safety.Tests.branch_uses_actual_instruction_target",
    "CIL.Safety.Tests.raw_address_cannot_be_scalar_argument",
    "CIL.Safety.Tests.reference_local_keeps_provenance",
    "CIL.Safety.expireAll_allocations",
    "CIL.Safety.leaveFrame_expires_owned",
    "CIL.Safety.allocateHome_preserves_wellFormed",
    "CIL.Safety.storeLocal_preserves_wellFormed",
    "CIL.Safety.leaveFrame_preserves_wellFormed",
    "CIL.Safety.run_success_step",
    "CIL.Safety.Tests.aggregate_argument_is_private_snapshot",
    "CIL.Safety.Tests.aggregate_argument_loads_complete_snapshot",
    "CIL.Safety.Tests.aggregate_home_reference_cannot_escape",
    "CIL.Safety.Tests.constructor_snapshot_survives_child_frame",
    "CIL.Safety.Tests.constructor_cannot_return_an_unexpected_value",
    "CIL.Safety.run_mono",
    "CIL.Safety.invoke_mono",
    "CIL.Safety.invoke_fault_refutes_success",
    "CIL.Safety.Tests.uninitialized_local_refutes_every_successful_fuel",
    "CIL.Safety.Tests.static_read_uses_bound_extracted_bytes",
    "CIL.Safety.Tests.static_store_rejected",
    "CIL.Safety.Tests.missing_static_identity_rejected",
    "CIL.Safety.Tests.static_instruction_bytes_must_match_metadata",
    "CIL.Safety.Tests.distinct_static_fields_keep_distinct_identities",
    "CIL.Safety.Tests.empty_span_reference_can_be_formed",
    "CIL.Safety.Tests.empty_span_reference_cannot_be_read",
    "CIL.Safety.cached_static_reference_checked",
    "CIL.Safety.makeLocal_preserves_wellFormed",
    "CIL.Safety.makeLocals_preserves_wellFormed",
    "CIL.Safety.makeArgumentHomes_preserves_wellFormed",
    "CIL.Safety.enterFrame_preserves_wellFormed",
    "CIL.Safety.staticReference_preserves_wellFormed",
    "CIL.Safety.staticInstruction_preserves_wellFormed",
    "CIL.Safety.storeValue_preserves_wellFormed",
    "CIL.Safety.memoryInstruction_preserves_wellFormed",
    "CIL.Safety.instruction_preserves_wellFormed",
    "CIL.Safety.step_preserves_wellFormed",
    "CIL.Safety.run_preserves_wellFormed",
    "CIL.Safety.invoke_preserves_wellFormed",
    "CIL.Safety.runVisits_wellFormed",
    "CIL.Safety.run_success_visits",
    "CIL.Safety.cached_static_reference_succeeds",
    "CIL.Safety.staticReference_succeeds",
    "CIL.Safety.empty_static_world_valid",
    "CIL.Safety.static_registry_fields_live",
    "CIL.Safety.makeLocal_fresh",
    "CIL.Safety.enterFrame_fresh",
    "CIL.Safety.leaveFrame_preserves_older_allocations",
    "CIL.Safety.frame_entry_exit_preserves_caller",
    "CIL.Safety.frame_entry_exit_preserves_reference",
    "CIL.Safety.Tests.private_frame_preserves_caller_reference",
    "CIL.Safety.AllocationExtension.preserves_reference",
    "CIL.Safety.makeLocals_owned",
    "CIL.Safety.enterFrame_owned",
    "CIL.Safety.leaveFrame_preserves_static_world",
    "CIL.Safety.step_extends_allocations",
    "CIL.Safety.step_ownedAbove",
    "CIL.Safety.run_preserves_caller_allocations",
    "CIL.Safety.invoke_preserves_caller_allocations",
    "CIL.Safety.invoke_preserves_caller_reference",
    "CIL.Safety.runVisits_preserves_caller_allocations",
    "CIL.Safety.runVisits_preserves_caller_reference",
    "CIL.Safety.step_preserves_frame_allocations",
    "CIL.Safety.child_run_preserves_parent_frame",
    "CIL.Safety.write_preserves_immutable",
    "CIL.Safety.allocate_preserves_immutable",
    "CIL.Safety.PreservesImmutable.binding",
    "CIL.Safety.PreservesImmutable.world",
    "CIL.Safety.initialized_lookup_cells",
    "CIL.Safety.staticReference_new_binding_valid",
    "CIL.Safety.staticReference_preserves_immutable",
    "CIL.Safety.staticReference_preserves_static_world",
    "CIL.Safety.staticReference_valid_result",
    "CIL.Safety.write_preserves_static_world",
    "CIL.Safety.memoryInstruction_preserves_static_world",
    "CIL.Safety.instruction_preserves_static_world",
    "CIL.Safety.staticInstruction_preserves_static_world",
    "CIL.Safety.allocateHome_preserves_static_world",
    "CIL.Safety.storeLocal_preserves_static_world",
    "CIL.Safety.enterFrame_preserves_static_world",
    "CIL.Safety.program_static_sites_valid",
    "CIL.Safety.step_preserves_static_world",
    "CIL.Safety.run_preserves_static_world",
    "CIL.Safety.invoke_preserves_static_world",
    "CIL.Safety.runVisits_preserves_static_world",
    "CIL.Safety.checkedValue_valid",
    "CIL.Safety.checkedValue_of_valid",
    "CIL.Safety.ValuesValid.preserve",
    "CIL.Safety.checkedValues_valid",
    "CIL.Safety.allocateHome_reference_valid",
    "CIL.Safety.storeLocal_preserves_reference_validity",
    "CIL.Safety.loadLocal_result_valid",
    "CIL.Safety.makeLocals_references_valid",
    "CIL.Safety.enterFrame_references_valid",
    "CIL.Safety.Frame.ReferencesValid.preserve",
    "CIL.Safety.run_result_valid",
    "CIL.Safety.invoke_result_valid",
    "CIL.Safety.enterFrame_live_state",
    "CIL.Safety.checked_entry_live_state",
    "CIL.Safety.child_preserves_parent_state",
    "CIL.Safety.child_resume_live_state",
    "CIL.Safety.loadValue_scalar_valid",
    "CIL.Safety.checked_add_result_valid",
    "CIL.Safety.memoryInstruction_values_valid",
    "CIL.Safety.instruction_values_valid",
    "CIL.Safety.access_reference_valid",
    "CIL.Safety.staticReference_reference_valid",
    "CIL.Safety.staticInstruction_values_valid",
    "CIL.Safety.stored_frame_references_valid",
    "CIL.Safety.step_preserves_frame_references",
    "CIL.Safety.allocated_store_reference_valid",
    "CIL.Safety.step_values_valid",
    "CIL.Safety.step_live_state",
    "CIL.Safety.programStep_live_state",
    "CIL.Safety.enter_child_live_state",
    "CIL.Safety.constructor_resume_live_state",
    "CIL.Safety.runningVisits_live_state",
    "CIL.Safety.runningVisits_memory_observation",
    "CIL.Safety.run_returned_state",
    "CIL.Safety.run_success_return_trace",
    "CIL.Safety.run_success_live_return_trace",
    "CIL.Safety.AccessRequirements.access",
    "CIL.Safety.read_snapshot",
    "CIL.Safety.read_result_snapshot",
    "CIL.Safety.permitted_by_view",
    "UInt256Model.Safety.byteNumber_snapshot",
    "UInt256Model.Safety.CallingConditions.of_requirements",
    "UInt256Model.Safety.CallingConditions.input_snapshot",
    "UInt256Model.Safety.CallingConditions.input_load",
    "UInt256Model.Safety.CallingConditions.binary_arguments_valid",
    "UInt256Model.Safety.CallingConditions.binary_entry_live",
    "UInt256Model.Safety.callerMemory_wellFormed",
    "UInt256Model.Safety.callerMemory_access",
    "UInt256Model.Safety.callerMemory_calling",
    "UInt256Model.Safety.caller_layouts_valid",
    "UInt256Model.Safety.caller_examples_nonvacuous",
    "UInt256Model.Safety.disjoint_output_unknown",
    "UInt256Model.Safety.partial_output_unknown_tail",
    "UInt256Model.Safety.partial_output_initialized_overlap",
    "CIL.Safety.allocateHome_succeeds",
    "CIL.Safety.allocateHome_write_access",
    "CIL.Safety.fresh_home_storeLocal_succeeds",
    "CIL.Safety.makeLocal_succeeds",
    "CIL.Safety.makeLocals_succeeds",
    "CIL.Safety.makeArgumentHomes_succeeds",
    "CIL.Safety.enterFrame_succeeds",
    "CIL.Safety.enterFrame_live_succeeds",
    "UInt256Model.Safety.CallingConditions.binary_setup_succeeds",
    "CIL.Safety.access_requirements",
    "CIL.Safety.AccessRequirements.slice",
    "CIL.Safety.read_slice",
    "CIL.Safety.AccessRequirements.add_slice",
    "UInt256Model.Safety.CallingConditions.input_limb_address",
    "UInt256Model.Safety.CallingConditions.input_limb_load",
    "UInt256Model.Safety.CallingConditions.input_field_instruction",
    "CIL.Safety.MemoryBelow.read",
    "CIL.Safety.allocate_preserves_memory_below",
    "CIL.Safety.write_preserves_memory_below",
    "CIL.Safety.allocateHome_preserves_caller_memory",
    "CIL.Safety.makeLocal_preserves_caller_memory",
    "CIL.Safety.makeLocals_preserves_caller_memory",
    "CIL.Safety.makeArgumentHomes_preserves_caller_memory",
    "CIL.Safety.enterFrame_preserves_caller_memory",
    "UInt256Model.Safety.CallingConditions.after_frame_setup",
    "UInt256Model.Safety.CallingConditions.after_memory_below",
    "UInt256Model.Safety.CallingConditions.input_bytes_of_memory_below",
    "UInt256Model.Safety.CallingConditions.input_value_after_setup",
    "UInt256Model.Safety.CallingConditions.input_field_after_setup",
    "CIL.Safety.write_outside",
    "CIL.Safety.write_preserves_initialization",
    "CIL.Safety.AccessRequirements.after_write",
    "CIL.Safety.write_preserves_readability",
    "CIL.Safety.write_readback",
    "CIL.Safety.WordHomes.weaken",
    "CIL.Safety.make_word_locals",
    "CIL.Safety.make_word_prefix",
    "CIL.Safety.certify_invocation",
    "CIL.Safety.WordHomes.length",
    "CIL.Safety.WordHomes.word_at",
    "CIL.Safety.WordHomes.word_bound",
    "CIL.Safety.WordHomes.ordered",

    "CIL.Safety.MemoryBelow.accessBelow",
    "CIL.Safety.AccessBelow.trans",
    "CIL.Safety.AccessBelow.weaken",
    "CIL.Safety.write_preserves_access_below",
    "CIL.Safety.AccessBelow.requirements",
    "CIL.Safety.AccessBelow.access",
    "CIL.Safety.AccessBelow.readable",
    "CIL.Safety.AccessBelow.read_eq",

    "CIL.Safety.write_word_outside",
    "CIL.Safety.run_next",
    "CIL.Safety.run_next_exists",
    "CIL.Safety.leaveFrame_preserves_memory_below",
    "CIL.Safety.decode_word64",
    "CIL.Safety.load_word64_of_read",
    "CIL.Safety.load_local_word64_of_read",
    "CIL.Safety.store_local_word64",
    "CIL.Safety.make_local_word64",
    "CIL.Safety.step_load_word64",
    "CIL.Safety.step_store_word64",
    "CIL.Safety.step_store_word64_same_frame",
    "CIL.Safety.run_call_of_invoke",
    "CIL.Safety.run_call_exists",
    "CIL.Safety.numberBytes_succ",
    "CIL.Safety.byteNumber_numberBytes",
    "UInt256Model.Safety.read_limb_number",
    "UInt256Model.Safety.output_value_of_limb_reads",
    "CIL.Safety.write_preserves_disjoint_read",
    "UInt256Model.Safety.CallingConditions.after_write",
    "UInt256Model.Safety.CallingConditions.output_limb_address",
    "UInt256Model.Safety.CallingConditions.write_output_slice",
    "UInt256Model.Safety.CallingConditions.output_field_instruction",
)


def main():
    sys.stdout.reconfigure(encoding="utf-8")
    lake = shutil.which("lake")
    if not lake:
        raise RuntimeError("Pinned Lean / lake must be on PATH")
    sources = [*sorted(source_files(VERIFY / "CIL", {".lean"})),
               *sorted(source_files(VERIFY / "UInt256/Safety", {".lean"})),
               VERIFY / "UInt256/Representation.lean",
               VERIFY / "UInt256/RepresentationLemmas.lean",
               Path(__file__).resolve(), VERIFY / "lean-toolchain", VERIFY / "common.py", VERIFY / "verify.py",
               VERIFY / "Tests/MemorySafety.lean", VERIFY / "Tests/MemorySafetyInstructions.lean"]
    identities = {str(p.relative_to(ROOT)): sha(p) for p in sources}
    started = time.perf_counter()
    with tempfile.TemporaryDirectory(prefix="int256-safety-foundation-") as temporary:
        proof = Path(temporary)
        for source in sources:
            destination = proof / source.relative_to(VERIFY)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
        (proof / "lakefile.toml").write_text(
            'name = "memory_safety_foundation"\nversion = "0.1.0"\n'
            '[[lean_lib]]\nname = "CIL"\n[[lean_lib]]\nname = "UInt256"\n'
            '[[lean_lib]]\nname = "Tests.MemorySafety"\n'
            '[[lean_lib]]\nname = "Tests.MemorySafetyInstructions"\n', encoding="utf-8")
        output = run([lake, "build", "+Tests.MemorySafetyInstructions:olean"], proof)
        audits = theorem_audits(output, AUDITS, ["propext", "Classical.choice", "Quot.sound"])
    if identities != {str(p.relative_to(ROOT)): sha(p) for p in sources}:
        raise RuntimeError("Safety source inputs changed during foundation checking")
    print(json.dumps({"kind": "safety-foundation", "productionCombined": False,
                      "elapsedSeconds": time.perf_counter() - started,
                      "sourceHashes": identities, "audits": audits}, indent=2))


if __name__ == "__main__":
    main()
