<Project>

  <PropertyGroup Condition="'$(EnableZkEvm)' == 'true'">
    <DefineConstants>$(DefineConstants);ZKEVM</DefineConstants>
  </PropertyGroup>

  <ItemGroup Condition="'$(EnableZkEvm)' == 'true'">
    <Compile Remove="**/*.std.cs" />
    <None Include="**/*.std.cs" />
  </ItemGroup>

  <ItemGroup Condition="'$(EnableZkEvm)' != 'true'">
    <Compile Remove="**/*.zkevm.cs" />
    <None Include="**/*.zkevm.cs" />
  </ItemGroup>

</Project>
