name: Build solutions

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

defaults:
  run:
    working-directory: src

env:
  BUILD_CONFIG: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7

    - name: Install dependencies
      run: |
        dotnet restore Int256.sln 

    - name: Build
      run: |
        dotnet build Int256.sln -c ${{ env.BUILD_CONFIG }} --no-restore
