name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    env:
      BUILD_CONFIG: release
    name: Test and publish
    runs-on: ubuntu-latest
    steps:
    
      - name: Check out repository
        uses: actions/checkout@v4
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v4

      - name: Install dependencies
        working-directory: src
        run: dotnet restore

      - name: Build
        working-directory: src/Nethermind.Int256
        run: dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore -p:Commit=$GITHUB_SHA
    
      - name: Test
        working-directory: src/Nethermind.Int256.Test
        run: dotnet test -c ${{ env.BUILD_CONFIG }} --no-restore

      - name: Publish
        working-directory: src/Nethermind.Int256
        run: |
          dotnet pack -c ${{ env.BUILD_CONFIG }} --no-build
          dotnet nuget push bin/${{ env.BUILD_CONFIG }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
