name: '[RUN] Int256 tests'

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
       - master
  pull_request:
  workflow_dispatch:

env:
  BUILD_CONFIG: release

jobs:
  int256-tests:
    name: 'Run Int256 tests'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7
    - name: Nethermind.Int256.Test
      run: |
        dotnet test src/Nethermind.Int256.Test/Nethermind.Int256.Test.csproj -c ${{ env.BUILD_CONFIG }}
